spring.application.name=ProfileManagerSpringBoot

# Database Connection (Supabase IPv4 Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.jkdmetikizzmnhqwnfqg
spring.datasource.password=pIz777Aksk3KZGOl
spring.datasource.driver-class-name=org.postgresql.Driver

# File Upload Limits
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# Supabase API & Storage Configuration
app.supabase.url=https://jkdmetikizzmnhqwnfqg.supabase.co
app.supabase.secret-key=sb_secret_CwiHYFtPRHGPp7Z3e7ZnsQ_7dWYpHDA
app.supabase.avatar-bucket=avatars